# Generated by Django 5.2 on 2025-12-11 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
        migrations.RenameModel(
            old_name='TypeOfProducts',
            new_name='TypeOfProduct',
        ),
    ]
