# Generated by Django 5.2.7 on 2026-02-12 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_product_popular'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typeofproduct',
            name='part',
        ),
        migrations.RemoveField(
            model_name='product',
            name='type',
        ),
        migrations.DeleteModel(
            name='Part',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='TypeOfProduct',
        ),
    ]
