# Generated by Django 5.2 on 2025-12-25 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'contact', 'verbose_name_plural': 'contact us'},
        ),
        migrations.RenameField(
            model_name='contactus',
            old_name='Message_text',
            new_name='admin_response',
        ),
        migrations.AddField(
            model_name='contactus',
            name='admin_response_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contactus',
            name='message_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
