# Generated by Django 5.2.7 on 2026-01-07 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0002_alter_contactus_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='mobile_number',
            field=models.TextField(blank=True, null=True),
        ),
    ]
