# Generated by Django 5.2.7 on 2026-08-09 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='price',
            new_name='final_price',
        ),
        migrations.AlterField(
            model_name='cart',
            name='payment_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
