# Generated by Django 5.2.7 on 2026-09-06 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province_name', models.CharField(blank=True, max_length=255, null=True)),
                ('province_code', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(blank=True, max_length=255, null=True)),
                ('city_code', models.CharField(blank=True, max_length=255, null=True)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.province')),
            ],
        ),
    ]
