# Generated by Django 5.2.7 on 2026-09-18 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_alter_city_options_alter_province_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'city', 'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='province',
            options={'verbose_name': 'province', 'verbose_name_plural': 'provinces'},
        ),
    ]
