# Generated by Django 5.2.7 on 2026-02-12 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='fjdslkfds', unique=True),
            preserve_default=False,
        ),
    ]
