# Generated by Django 5.2.7 on 2026-06-18 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_productcolor_productreview_productspecification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeofproduct',
            name='part',
            field=models.ManyToManyField(blank=True, to='product.part'),
        ),
    ]
