# Generated by Django 5.2.7 on 2026-09-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='admin_verifed',
            field=models.BooleanField(default=False),
        ),
    ]
