# Generated by Django 5.2.7 on 2026-09-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_productreview_admin_verifed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.PositiveIntegerField(choices=[(1, 'ضعیف'), (2, 'متوسط'), (3, 'خوب'), (4, 'خیلی خوب'), (5, 'عالی')], default=0),
        ),
    ]
